# Generated by Django 2.0.2 on 2018-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principal',
            new_name='head',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='not available', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.CharField(default='not available', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='interest',
            field=models.CharField(default='not available', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='not available', max_length=256),
        ),
    ]
