# Generated by Django 2.0.2 on 2018-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180603_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project_current',
            field=models.CharField(default='not available', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='project_done',
            field=models.CharField(default='not available', max_length=256),
        ),
    ]
